### ISSUE TITLE
Rebuild 3D transform interactives.

### ISSUE THREAD

**Issue by courtneycb** [uccser/cs-field-guide#1115]
The archived interactives in the computer graphics chapter should be rebuilt for the Django system.

There are 2 main interactives, one with multiple versions:

- [x] Scene Editor
    - [x]  3D transform matrix 
    - [x]  3D translation matrix 
    - [x]  3D with multiple matrices and vectors
    - [x]  Scene creation

- [x] Matrix Simplifier

**TODO/suggestions**

- [x]  Need to look into adding copy funcitonality to matrix simplifier so we can copy matrices into scene editor.
- [x] Add remove all button to Matrix Simplifier

**Comment by eAlasdair** [comment]
This is a superset of #374 so I'll close that one

**Comment by eAlasdair** [comment]
And the remaining interactive is covered in #375
