### ISSUE TITLE
Update interactives for Django system

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#622]
- [x] 2d-arrow-manipulations (**Renamed 2d-shape-manipulations** (see #863))
- [x] action-menu
- [x] available-menu-items
- [x] awful-calculator
- [x] base-calculator
- [x] big-number-calculator @courtneycb
- [x] binary-cards @courtneycb
- [x] bin-packing
- [x] box-rotation
- [x] box-translation
- [x] caesar-cipher **coffeescript**
- [x] checksum-calculator @courtneycb
- [x] checksum-calculator-gtin-13 @courtneycb
- [x] close-window @courtneycb
- [x] cmy-mixer @courtneycb
- [x] colour-matcher @courtneycb
- [x] compression-comparer @courtneycb
- [x] confused-buttons @courtneycb
- [x] date-picker
- [x] deceiver @courtneycb
- [x] delay-analyser @courtneycb
- [x] delayed-checkbox @courtneycb
- [x] frequency-analysis @courtneycb **coffeescript**
- [x] fsa-box @courtneycb
- [x] fsa-light @courtneycb
- [x] fsa-washing-machine @courtneycb
- [x] hex-background-colour @courtneycb
- [x] high-score-boxes
- [x] huffman-tree @courtneycb
- [x] image-bit-comparer @courtneycb
- [x] jpeg-compression
- [x] MD5-hash @courtneycb (**Deleted in #984**)
- [x] mips-assembler
- [x] mips-simulator
- [x] ncea-guide-selector (**Deleted in #958**)
- [x] nfa-guesser
- [x] no-help @courtneycb 
- [x] number-generator @courtneycb
- [x] packet-attack
- [x] packet-attack-level-creator
- [x] parity @courtneycb
- [x] payment-interface @courtneycb
- [x] pixel-viewer
- [x] python-interpreter
- [x] regular-expression-filter
- [x] regular-expression-search
- [x] rgb-mixer @courtneycb
- [x] rsa-jsencrypt
- [x] rsa-key-generator 
- [x] rsa-no-padding
- [x] run-length-encoding
- [x] searching-algorithms
- [x] sha2 **coffeescript**
- [x] sorting-algorithm-comparison @courtneycb
- [x] sorting-algorithms
- [x] starter-structure (not doing)
- [x] trainsylvania @courtneycb
- [x] trainsylvania-planner @courtneycb
- [x] trig-function-calculator
- [x] unicode-binary @courtneycb 
- [x] unicode-chars @courtneycb
- [x] unicode-length @courtneycb
- [x] viola-jones-face-detector
- [x] ziv-lempel-coding @hayleyavw (**potentially removed** #909)
