### ISSUE TITLE
Deal with old github branches

### ISSUE THREAD

**Issue by eAlasdair** [uccser/cs-field-guide#979]
By 'no different' I mean the branch is many commits behind develop but doesn't add anything new to it. This indicates the changes were merged into develop but the branch was not removed. Branches with current PRs are excluded

## Branches that are 'No Different'

- [ ] `homepage-design` & `homepage-design-v2`
- [ ] `issue/12` #12
- [ ] `issue/422` #422
- [ ] `issue/436` #436
- [ ] `issue/706-searching-algorithms-interactive` #706
- [ ] `issue/813` (#813)
- [ ]  `issue/826` (#826)
- [ ] `issue/867` (#867)
- [ ] `issue/898` (#898)
- [ ] `pyup/*` (15 branches)
- [ ] `remove-admin`
- [ ] `rsa-key-generator-refactor`
- [ ] `sneak peek`
- [ ] `sorting-algorithms-refactor`

## Branches last updated pre-2017

- [ ] `content/encryption`: 8 commits by Heidirose & JackMorganNZ May-Jul 2016
- [ ] `dynamic-system`: 4 commits by jordangriffiths01 Aug 2016
- [ ] `html-generator`: 1 commit by JackMorganNZ May 2016
- [ ] `interactive-audio-zoom`: 13 commits by Jamesernator Jul-Oct 2016
- [ ] `interactive-network-simulation`: 19 commits by Jamesernator Dec 2015-Jan 2016
- [ ] `interactive-turing-machine`: 1 commit by Jamesernator Jan 2016
- [ ] `pdf-generator`: 3 commits by JackMorganNZ & jordangriffiths01 Jul 2015-Feb 2016
- [ ] `style-checker`: 3 commits by JackMorganNZ Mar-Apr 2016

## Branches last updated 2017

- [ ] `content/complexity-tractability`: 3 commits by hayleyavw Feb-Mar 2017
- [ ] `content/computer-vision`: 14 commits by ravenmaster001 Mar-Jul 2017
- [ ] `interactive/image-filters`: 17 commits by ravenmaster001 Mar-Aug 2017
- [ ] `interactive-tree-simulator`: 1 commit by JackMorganNZ Oct 2017

## Branches last updated 2018

- [ ] `automate-deployment`: 1 commit by JackMorganNZ Mar 2018
- [ ] `frequency-analysis-refactor`: 1 commit by courtneycb Aug 2018
- [ ] `issue/480`: 3 commits by JackMorganNZ Sep 2017-Jan 2018 (#480)
- [ ] `issue/830`: 1 commit by courtneycb Dec 2018 (#830)
- [ ] `issue/835`: 5 commits by courtneycb Dec 2018-Jan 2019 (#835)
- [ ] `pixel-viewer-refactor`: 2 commits by courtneycb & eAlasdair Jul-Dec 2018
- [ ] `ui-update-1`: 4 commits by JackMorgan Jun 2018

## Branches last updated 2019

- [ ] `big-time-calculator-interactive`: 1 commit by courtneycb Jan 2019
- [ ] `issue/783`: 7 commits by eAlasdair Nov 2018-Feb 2019 (#783, #806)
- [ ] `issue/846`: 3 commits by courtneycb Jan 2019 (#846)

**Comment by eAlasdair** [comment]
Branches that are 'no different', plus `frequency-analysis-refactor`, `pixel-viewer-refactor` and `issue/783` have been deleted
